services:
  - type: web
    name: gymmentor-ar-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: python manage.py migrate && gunicorn gymmentor_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
