# Generated by Django 6.1.1 on 2026-10-01 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(default='Bodyweight Squats', max_length=100)),
                ('total_reps', models.IntegerField(default=0)),
                ('good_reps', models.IntegerField(default=0)),
                ('flagged_reps', models.IntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('start_time', models.BigIntegerField(blank=True, help_text='Timestamp in ms', null=True)),
                ('end_time', models.BigIntegerField(blank=True, help_text='Timestamp in ms', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_number', models.IntegerField()),
                ('is_good', models.BooleanField(default=True)),
                ('min_knee_angle', models.FloatField(help_text='Lowest knee angle in degrees')),
                ('duration_ms', models.IntegerField(default=0, help_text='Rep duration in ms')),
                ('issues', models.JSONField(blank=True, default=list, help_text='List of detected form issues')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_history', to='workouts.workoutsession')),
            ],
            options={
                'ordering': ['rep_number'],
            },
        ),
    ]
