# Generated by Django 6.1.1 on 2026-10-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repdetail',
            name='is_perfect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repdetail',
            name='score',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='perfect_reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='username',
            field=models.CharField(db_index=True, default='Athlete', max_length=100),
        ),
    ]
