# Generated by Django 6.1.1 on 2026-10-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_repdetail_is_perfect_repdetail_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repdetail',
            name='lowest_score',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='repdetail',
            name='snapshot_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repdetail',
            name='snapshot_image',
            field=models.TextField(blank=True, help_text='Base64 snapshot of mistake / lowest score', null=True),
        ),
        migrations.AddField(
            model_name='repdetail',
            name='snapshot_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
